version: '1.29'


networks:
  huggingFaceNet:
    driver: bridge

services:
    # Base de données mongo
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    container_name: mongodb
    restart: always
    networks:
      - huggingFaceNet


  # scraper du site Hugging Face
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile_scraper
    depends_on:
      - mongodb
    networks:
        - huggingFaceNet

  # Application dash
  dash_app:
    build:
      context: ./dash
      dockerfile: Dockerfile_dash
    ports:
      - "8050:8050"
    depends_on:
      scraper:
        condition: service_completed_successfully
    networks:
        - huggingFaceNet