# FastAPI Dockerfile-FastAPI-Scraper
FROM python:3.11.2

WORKDIR /app

COPY Pipfile /app/Pipfile
COPY Pipfile.lock /app/Pipfile.lock

RUN pip install pipenv && pipenv install --system --deploy

COPY FastAPI /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]